### PR TITLE
fix MSCHAPv2 EAP when using OpenSSL 3.0

### PR DESCRIPTION
**Pull request by socram8888**
Ubuntu ships, since 22.04, with OpenSSL 3.0, which is in theory fully backwards compatible with 1.1.0 from an API standpoint.

However, in 3.0 the "legacy" provider is not automatically enabled. Without enabling it, the EVP_md4 call still exists and returns a value, but throws an error in the mschap_ntpassword_hash function during the call to EVP_DigestUpdate with said context, which causes OpenIKED to detect an unexpected error condition and shut itself down:

```
ikev2_msg_decrypt: decrypted payload length 80/80 padding 10
00000045 02010041 1a020100 3c31f5df e58a84c9 c38f1ffd 2f30aa6d 0d110000
00000000 00007630 638759fe 70dfa716 2dc8895b 15850cd4 70103e4f ce5f006d
6172636f 73000000 00000000 0000000a
ikev2_pld_payloads: decrypted payload EAP nextpayload NONE critical 0x00 length 69
spi=0x943e92b2486ee974: ikev2_pld_eap: RESPONSE id 1 length 65 EAP-MSCHAP_V2
eap_parse: MSCHAP_V2 RESPONSE id 1 length 60 valuesize 49 name 'marcos' name-length 6
f5dfe58a 84c9c38f 1ffd2f30 aa6d0d11 00000000 00000000 76306387 59fe70df
a7162dc8 895b1585 0cd47010 3e4fce5f 00
sa_stateok: SA_INIT flags 0x0000, require 0x0000
control exiting, pid 12101
12099 parent exiting
ca exiting, pid 12100
parent terminating
```

This PR uses the reported OpenSSL version to use the old, deprecated engine concept for <3.0, and the new provider concept if using >=3.0.

Compiling against OpenSSL 3.0 still throws some deprecation warnings, but those do not prevent the application from working and could be addressed in a future update.

### CODE REVIEW

**Comment by tobhe** [comment]
Thank you for the fix! I would of course prefer to not have OpenSSL ifdefs but the design of the 3.0 API doesn't seem to give us a better choice. One alternative I see is loading the provider via config file but that would require manually modifying the OpenSSL config to use mschapv2 which is also not ideal from a UX point of view.

**Comment by socram8888** [comment]
Problem with this #ifdef approach is that it would work incorrectly if compiled against 1.* and then executed using 3.*, but I think that here OpenSSL is to blame for breaking backwards compatibility.

Maybe it could be possible to do some shenanigans with dlopen and dynamically calling the provider_* functions if OpenSSL if 3.0 or newer.

**Comment by ip75** [comment]
```
-> # iked -V
OpenIKED 7.4
```

```
-> # iked -dv
iked: error enabling legacy provider: No such process
```

```
-> # openssl version
OpenSSL 3.0.16 11 Feb 2025 (Library: OpenSSL 3.0.16 11 Feb 2025)
```

```
-> # uname -a
FreeBSD 14.2-RELEASE-p5 FreeBSD 14.2-RELEASE-p5 releng/14.2-n269533-0781dd1545f6 amd64
```

I've rebuilt openssl with legacy support, and iked started without this error.

@socram8888

**Comment by tobhe** [comment]
Is the legacy provider an optional package? Are you sure it is installed on your system? Maybe we shouldn't `fatal` in this case but only print a warning.

**Comment by ip75** [comment]
iked does not know how to associate certificates from the `ca` directory and private keys from the `private` directory. It's a pity. 
when I try to connect i get error:
```
spi=0x2adb166e98fd412a: sa_free: authentication failed
spi=0x2adb166e98fd412a: ca_getreq: found cert with matching ID but without matching key.
```
Basic functionality does not work correctly. I've removed it and by by iked.

**Pull request merged**
